### ISSUE TITLE
编译不过去

### ISSUE THREAD

**Issue by loyalpartner** [zhangkaiser/librime-wasm#2]
系统 ubuntu 22.0

安装了下面的依赖
```
apt install libboost-dev \
  libboost-filesystem-dev \
  libboost-regex-dev \
  libboost-system-dev \
  libyaml-cpp-dev \
  libleveldb-dev \
  libmarisa-dev \
  libopencc-dev
```
我也将 EM_CMAKE_PATH 换成了自己路径

我的 操作步骤：

```bash
❯ npm run librime

> librime@1.7.3 librime /home/lee/projects/zhime/librime
> npm run set:env && npm run emscripten:cmake-adapter && emmake make librime && npm run emscripten:cmake-revert


> librime@1.7.3 set:env /home/lee/projects/zhime/librime
> export EM_CMAKE_PATH=/home/ubuntu/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake


> librime@1.7.3 emscripten:cmake-adapter /home/lee/projects/zhime/librime
> bash ./emscripten/cmake-adapter.sh

make: make librime
emcmake cmake . -Bbuild \
-DCMAKE_INSTALL_PREFIX=/usr \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_MERGED_PLUGINS=OFF \
-DENABLE_EXTERNAL_PLUGINS=OFF \
-DBUILD_TEST=OFF \
-DBUILD_STATIC=ON \
-DBUILD_SHARED_LIBS=OFF \
-DBOOST_USE_SIGNALS2=ON \
-DENABLE_LOGGING=ON \
-DBOOST_USE_CXX11=ON \
-DCMAKE_TOOLCHAIN_FILE=/home/ubuntu/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
-DCMAKE_CXX_FLAGS=" -pthread" \
-DBOOST_INCLUDEDIR:FILEPATH=/home/lee/projects/zhime/librime/deps/boost/include \
-DBOOST_LIBRARYDIR:FILEPATH=/home/lee/projects/zhime/librime/deps/boost/lib
configure: cmake . -Bbuild -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DBUILD_MERGED_PLUGINS=OFF -DENABLE_EXTERNAL_PLUGINS=OFF -DBUILD_TEST=OFF -DBUILD_STATIC=ON -DBUILD_SHARED_LIBS=OFF -DBOOST_USE_SIGNALS2=ON -DENABLE_LOGGING=ON -DBOOST_USE_CXX11=ON -DCMAKE_TOOLCHAIN_FILE=/home/ubuntu/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake "-DCMAKE_CXX_FLAGS= -pthread" -DBOOST_INCLUDEDIR:FILEPATH=/home/lee/projects/zhime/librime/deps/boost/include -DBOOST_LIBRARYDIR:FILEPATH=/home/lee/projects/zhime/librime/deps/boost/lib -DCMAKE_CROSSCOMPILING_EMULATOR=/home/lee/projects/emsdk/node/14.18.2_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads
-- Found glog: /home/lee/projects/zhime/librime/deps/lib/libglog.a
-- Found yaml-cpp: /home/lee/projects/zhime/librime/deps/lib/libyaml-cpp.a
-- Found leveldb: /home/lee/projects/zhime/librime/deps/lib/libleveldb.a
-- Found marisa: /home/lee/projects/zhime/librime/deps/lib/libmarisa.a
-- Found opencc: /home/lee/projects/zhime/librime/deps/lib/libopencc.a
-- Found X11/keysym.h at /home/lee/projects/emsdk/upstream/emscripten/cache/sysroot/include
-- rime_plugins_libs:
-- rime_plugins_modules:
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lee/projects/zhime/librime/build
cmake --build build
make: cmake: Permission denied
make: *** [Makefile:47: release] Error 127
emmake: error: 'make librime' failed (returned 2)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! librime@1.7.3 librime: `npm run set:env && npm run emscripten:cmake-adapter && emmake make librime && npm run emscripten:cmake-revert`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the librime@1.7.3 librime script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee/.npm/_logs/2023-03-04T08_42_43_000Z-debug.log
```

```bash
npm install
npm build:deps
npm run build
```

输出

```
❯ npm run build

> librime@1.7.3 build /home/lee/projects/zhime/librime
> npm run build:deps && npm run build:noEvalWorkerDecoder


> librime@1.7.3 build:deps /home/lee/projects/zhime/librime
> rimraf out && mkdir out && mkdir out/worker && rollup -c && cp -r ./emscripten/asset/* ./out/


emscripten/chrome-extension.ts → out/index.js...
(!) Plugin typescript: @rollup/plugin-typescript: Rollup 'sourcemap' option must be set to generate source maps.
created out/index.js in 3.9s

emscripten/options.ts, emscripten/mv3-background.ts, emscripten/mv3-main.ts → out...
(!) Plugin typescript: @rollup/plugin-typescript: Rollup 'sourcemap' option must be set to generate source maps.
created out in 3.2s

> librime@1.7.3 build:noEvalWorkerDecoder /home/lee/projects/zhime/librime
> npm run build:workerDecoder -- -sDYNAMIC_EXECUTION=0


> librime@1.7.3 build:workerDecoder /home/lee/projects/zhime/librime
> npm run build:webDecoder -- -pthread -o ./out/worker/pthread.js -sPTHREAD_POOL_SIZE_STRICT=2 -sPTHREAD_POOL_SIZE=2 "-sDYNAMIC_EXECUTION=0"


> librime@1.7.3 build:webDecoder /home/lee/projects/zhime/librime
> npm run build:wasmdeps -- ./emscripten/decoder.cc -lembind -lidbfs.js --pre-js ./out/index.js --post-js emscripten/post.js "-pthread" "-o" "./out/worker/pthread.js" "-sPTHREAD_POOL_SIZE_STRICT=2" "-sPTHREAD_POOL_SIZE=2" "-sDYNAMIC_EXECUTION=0"


> librime@1.7.3 build:wasmdeps /home/lee/projects/zhime/librime
> npm run build:wasminclude -- -L./build/lib -lrime -L./deps/boost/lib -lboost_signals -lboost_filesystem -lboost_regex -lboost_system -lboost_locale -L./deps/lib -lleveldb -lmarisa -lopencc -lyaml-cpp -lglog "./emscripten/decoder.cc" "-lembind" "-lidbfs.js" "--pre-js" "./out/index.js" "--post-js" "emscripten/post.js" "-pthread" "-o" "./out/worker/pthread.js" "-sPTHREAD_POOL_SIZE_STRICT=2" "-sPTHREAD_POOL_SIZE=2" "-sDYNAMIC_EXECUTION=0"


> librime@1.7.3 build:wasminclude /home/lee/projects/zhime/librime
> npm run build:wasmsettings -- -I./src/ -I./build/src/ -I./deps/boost/include -I./deps/include "-L./build/lib" "-lrime" "-L./deps/boost/lib" "-lboost_signals" "-lboost_filesystem" "-lboost_regex" "-lboost_system" "-lboost_locale" "-L./deps/lib" "-lleveldb" "-lmarisa" "-lopencc" "-lyaml-cpp" "-lglog" "./emscripten/decoder.cc" "-lembind" "-lidbfs.js" "--pre-js" "./out/index.js" "--post-js" "emscripten/post.js" "-pthread" "-o" "./out/worker/pthread.js" "-sPTHREAD_POOL_SIZE_STRICT=2" "-sPTHREAD_POOL_SIZE=2" "-sDYNAMIC_EXECUTION=0"


> librime@1.7.3 build:wasmsettings /home/lee/projects/zhime/librime
> npm run build:wasmbase -- -sWASM_BIGINT -sASSERTIONS -sDISABLE_EXCEPTION_CATCHING=0 -sERROR_ON_UNDEFINED_SYMBOLS=0 -sINITIAL_MEMORY=256MB "-I./src/" "-I./build/src/" "-I./deps/boost/include" "-I./deps/include" "-L./build/lib" "-lrime" "-L./deps/boost/lib" "-lboost_signals" "-lboost_filesystem" "-lboost_regex" "-lboost_system" "-lboost_locale" "-L./deps/lib" "-lleveldb" "-lmarisa" "-lopencc" "-lyaml-cpp" "-lglog" "./emscripten/decoder.cc" "-lembind" "-lidbfs.js" "--pre-js" "./out/index.js" "--post-js" "emscripten/post.js" "-pthread" "-o" "./out/worker/pthread.js" "-sPTHREAD_POOL_SIZE_STRICT=2" "-sPTHREAD_POOL_SIZE=2" "-sDYNAMIC_EXECUTION=0"


> librime@1.7.3 build:wasmbase /home/lee/projects/zhime/librime
> emcc -std=c++14 -Wall -Wno-js-compiler -Wno-deprecated-builtins -Wno-deprecated-declarations "-sWASM_BIGINT" "-sASSERTIONS" "-sDISABLE_EXCEPTION_CATCHING=0" "-sERROR_ON_UNDEFINED_SYMBOLS=0" "-sINITIAL_MEMORY=256MB" "-I./src/" "-I./build/src/" "-I./deps/boost/include" "-I./deps/include" "-L./build/lib" "-lrime" "-L./deps/boost/lib" "-lboost_signals" "-lboost_filesystem" "-lboost_regex" "-lboost_system" "-lboost_locale" "-L./deps/lib" "-lleveldb" "-lmarisa" "-lopencc" "-lyaml-cpp" "-lglog" "./emscripten/decoder.cc" "-lembind" "-lidbfs.js" "--pre-js" "./out/index.js" "--post-js" "emscripten/post.js" "-pthread" "-o" "./out/worker/pthread.js" "-sPTHREAD_POOL_SIZE_STRICT=2" "-sPTHREAD_POOL_SIZE=2" "-sDYNAMIC_EXECUTION=0"

warning: undefined symbol: shmdt (referenced by top-level compiled C/C++ code)
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/
with a log of the build and the input files used to run. Exception message: "In the following macro:

 preJS()

Error: /home/lee/projects/zhime/librime/out/index.js:163: Unknown preprocessor directive #decoder;
    at preprocess (/home/lee/projects/emsdk/upstream/emscripten/src/parseTools.js:137:17)
    at preJS (/home/lee/projects/emsdk/upstream/emscripten/src/parseTools.js:994:15)
    at eval (eval at <anonymous> (/home/lee/projects/emsdk/upstream/emscripten/src/parseTools.js), <anonymous>:1:2)
    at eval (/home/lee/projects/emsdk/upstream/emscripten/src/parseTools.js:25:19)
    at String.replace (<anonymous>)
    at processMacros (/home/lee/projects/emsdk/upstream/emscripten/src/parseTools.js:23:15)
    at includeFile (/home/lee/projects/emsdk/upstream/emscripten/src/jsifier.js:456:11)
    at finalCombiner (/home/lee/projects/emsdk/upstream/emscripten/src/jsifier.js:483:5)
    at runJSify (/home/lee/projects/emsdk/upstream/emscripten/src/jsifier.js:552:3)
    at Object.<anonymous> (/home/lee/projects/emsdk/upstream/emscripten/src/compiler.js:97:3)
emcc: error: '/home/lee/projects/emsdk/node/14.18.2_64bit/bin/node /home/lee/projects/emsdk/upstream/emscripten/src/compiler.js /tmp/tmp2plui64v.json' failed (returned 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! librime@1.7.3 build:wasmbase: `emcc -std=c++14 -Wall -Wno-js-compiler -Wno-deprecated-builtins -Wno-deprecated-declarations "-sWASM_BIGINT" "-sASSERTIONS" "-sDISABLE_EXCEPTION_CATCHING=0" "-sERROR_ON_UNDEFINED_SYMBOLS=0" "-sINITIAL_MEMORY=256MB" "-I./src/" "-I./build/src/" "-I./deps/boost/include" "-I./deps/include" "-L./build/lib" "-lrime" "-L./deps/boost/lib" "-lboost_signals" "-lboost_filesystem" "-lboost_regex" "-lboost_system" "-lboost_locale" "-L./deps/lib" "-lleveldb" "-lmarisa" "-lopencc" "-lyaml-cpp" "-lglog" "./emscripten/decoder.cc" "-lembind" "-lidbfs.js" "--pre-js" "./out/index.js" "--post-js" "emscripten/post.js" "-pthread" "-o" "./out/worker/pthread.js" "-sPTHREAD_POOL_SIZE_STRICT=2" "-sPTHREAD_POOL_SIZE=2" "-sDYNAMIC_EXECUTION=0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the librime@1.7.3 build:wasmbase script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee/.npm/_logs/2023-03-04T08_36_43_040Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! librime@1.7.3 build:wasmsettings: `npm run build:wasmbase -- -sWASM_BIGINT -sASSERTIONS -sDISABLE_EXCEPTION_CATCHING=0 -sERROR_ON_UNDEFINED_SYMBOLS=0 -sINITIAL_MEMORY=256MB "-I./src/" "-I./build/src/" "-I./deps/boost/include" "-I./deps/include" "-L./build/lib" "-lrime" "-L./deps/boost/lib" "-lboost_signals" "-lboost_filesystem" "-lboost_regex" "-lboost_system" "-lboost_locale" "-L./deps/lib" "-lleveldb" "-lmarisa" "-lopencc" "-lyaml-cpp" "-lglog" "./emscripten/decoder.cc" "-lembind" "-lidbfs.js" "--pre-js" "./out/index.js" "--post-js" "emscripten/post.js" "-pthread" "-o" "./out/worker/pthread.js" "-sPTHREAD_POOL_SIZE_STRICT=2" "-sPTHREAD_POOL_SIZE=2" "-sDYNAMIC_EXECUTION=0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the librime@1.7.3 build:wasmsettings script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee/.npm/_logs/2023-03-04T08_36_43_080Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! librime@1.7.3 build:wasminclude: `npm run build:wasmsettings -- -I./src/ -I./build/src/ -I./deps/boost/include -I./deps/include "-L./build/lib" "-lrime" "-L./deps/boost/lib" "-lboost_signals" "-lboost_filesystem" "-lboost_regex" "-lboost_system" "-lboost_locale" "-L./deps/lib" "-lleveldb" "-lmarisa" "-lopencc" "-lyaml-cpp" "-lglog" "./emscripten/decoder.cc" "-lembind" "-lidbfs.js" "--pre-js" "./out/index.js" "--post-js" "emscripten/post.js" "-pthread" "-o" "./out/worker/pthread.js" "-sPTHREAD_POOL_SIZE_STRICT=2" "-sPTHREAD_POOL_SIZE=2" "-sDYNAMIC_EXECUTION=0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the librime@1.7.3 build:wasminclude script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee/.npm/_logs/2023-03-04T08_36_43_144Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! librime@1.7.3 build:wasmdeps: `npm run build:wasminclude -- -L./build/lib -lrime -L./deps/boost/lib -lboost_signals -lboost_filesystem -lboost_regex -lboost_system -lboost_locale -L./deps/lib -lleveldb -lmarisa -lopencc -lyaml-cpp -lglog "./emscripten/decoder.cc" "-lembind" "-lidbfs.js" "--pre-js" "./out/index.js" "--post-js" "emscripten/post.js" "-pthread" "-o" "./out/worker/pthread.js" "-sPTHREAD_POOL_SIZE_STRICT=2" "-sPTHREAD_POOL_SIZE=2" "-sDYNAMIC_EXECUTION=0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the librime@1.7.3 build:wasmdeps script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee/.npm/_logs/2023-03-04T08_36_43_178Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! librime@1.7.3 build:webDecoder: `npm run build:wasmdeps -- ./emscripten/decoder.cc -lembind -lidbfs.js --pre-js ./out/index.js --post-js emscripten/post.js "-pthread" "-o" "./out/worker/pthread.js" "-sPTHREAD_POOL_SIZE_STRICT=2" "-sPTHREAD_POOL_SIZE=2" "-sDYNAMIC_EXECUTION=0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the librime@1.7.3 build:webDecoder script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee/.npm/_logs/2023-03-04T08_36_43_210Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! librime@1.7.3 build:workerDecoder: `npm run build:webDecoder -- -pthread -o ./out/worker/pthread.js -sPTHREAD_POOL_SIZE_STRICT=2 -sPTHREAD_POOL_SIZE=2 "-sDYNAMIC_EXECUTION=0"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the librime@1.7.3 build:workerDecoder script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee/.npm/_logs/2023-03-04T08_36_43_242Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! librime@1.7.3 build:noEvalWorkerDecoder: `npm run build:workerDecoder -- -sDYNAMIC_EXECUTION=0`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the librime@1.7.3 build:noEvalWorkerDecoder script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee/.npm/_logs/2023-03-04T08_36_43_270Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! librime@1.7.3 build: `npm run build:deps && npm run build:noEvalWorkerDecoder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the librime@1.7.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lee/.npm/_logs/2023-03-04T08_36_43_298Z-debug.log
```

**Comment by zhangkaiser** [comment]
- 第一个错误报构建`librime`库时时 `cmake权限问题`，可以尝试使用`sudo`进行构建
- 第二个错误是Emscripten在构建JS库时的错误，根据描述是未对JS的`#decoder`新语法支持导致编译器指令错误，这种可以是Emscripten版本过低导致，可以尝试升级/降级Emscripten版本或者将emscripten/*.ts文件中的#decoder变为_decoder尝试。

**Comment by loyalpartner** [comment]
感谢回复！

第二个错误 我尝试过将 emsdk 最新的版本，和 3.0.0 

最新的版本 报的错就是上面的错误
换成 3.0.0 后  错误变成 unknown file type: service.cc.o

能提供一下你这边 emsdk 的版本吗？

**Comment by zhangkaiser** [comment]
上面的错误可以清除librime目录下的cmake生成的缓存再尝试。

我这里使用的emcc版本是**3.1.26**

**Comment by loyalpartner** [comment]
我将 emsdk 切换到 3.1.26 后，emcc 编译通过了， 再次表示感谢！
